version: '2'
services:
  ckan:
    container_name : ckan
    build: ./web/
    entrypoint: ./web/docker-entrypoint.sh
    ports:
     - "5000:5000"
    env_file:
     - ./secrets.env
    volumes:
     - ./data/ckan_storage:/var/lib/postgresql/data/ckan
    depends_on:
     - solr
    environment:
       DATABASE_URL: "postgresql://ckan:ckan@postgres:5432/ckan"
       SOLR_URL: "http://solr:8983/solr/ckan"
  solr:
    image: ckan/solr:latest