version: '2'
services:
  nginx:
    image: nginx:1.11.8
    ports:
     - "80:80"
    volumes:
     - ./nginx/odp.conf:/etc/nginx/conf.d/default.conf
  ckan:
    container_name : ckan
    build: ./ckan/
    entrypoint: /docker-entrypoint.sh
    ports:
     - "8080:8080"
    env_file:
     - ./secrets.env
    volumes:
     - ./data/ckan_storage:/var/lib/postgresql/data/ckan
    depends_on:
     - solr
    environment:
       POSTGRES_HOST: "${POSTGRES_HOST}"
       POSTGRES_PORT: "${POSTGRES_PORT}"
       POSTGRES_USER: "${POSTGRES_USER}"
       POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
       POSTGRES_DATASTORE_USER: "${POSTGRES_DATASTORE_USER}"
       POSTGRES_DATASTORE_PASSWORD: "${POSTGRES_DATASTORE_PASSWORD}"
       PGPASSWORD: "${POSTGRES_PASSWORD}"
       POSTGRES_CKAN_DBNAME: "${POSTGRES_CKAN_DBNAME}"
       POSTGRES_CKAN_DATASTORE_DBNAME: "${POSTGRES_CKAN_DATASTORE_DBNAME}"
       CKAN_SQLALCHEMY_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_CKAN_DBNAME}"
       CKAN_DATASTORE_WRITE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_CKAN_DATASTORE_DBNAME}"
       CKAN_DATASTORE_READ_URL: "postgresql://${POSTGRES_DATASTORE_USER}:${POSTGRES_DATASTORE_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_CKAN_DATASTORE_DBNAME}"
       CKAN_SITE_URL: "${CKAN_SITE_URL}"
       CKAN_SITE_ID: "default"
       CKAN_STORAGE_PATH: "/var/lib/ckan"
       CKAN_DATAPUSHER_URL: "http://127.0.0.1:8800/"
       CKAN_SOLR_URL: "http://solr:8983/solr/${POSTGRES_CKAN_DBNAME}"
       SOLR_URL: "http://solr:8983/solr/${POSTGRES_CKAN_DBNAME}"
  solr:
    image: ckan/solr:latest
    ports:
     - "8983:8983"
