version: '2'
services:
  nginx:
    restart: always
    logging:
      options:
        max-size: '100m'
  ckan:
    restart: always
    logging:
      options:
        max-size: '100m'
  datapusher:
    restart: always
    logging:
      options:
        max-size: '100m'
  solr:
    restart: always
    logging:
      options:
        max-size: '100m'
